/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DialogInfo: typeof import('./../components/DialogInfo/index.vue')['default']
    FileUpload: typeof import('./../components/FileUpload/index.vue')['default']
    Layout: typeof import('./../components/Layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTable: typeof import('./../components/SearchTable/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  }
}
